### ISSUE TITLE
Surface assisted cortical parcellation

### ISSUE THREAD

**Issue by Sunderlandkyl** [PerkLab/NeuroSegmentation#4]
Implement surface assisted cortical parcellation in 3D Slicer.

[Surface assisted cortical parcellation manual](https://www.dropbox.com/s/go5q8p49akuj4p8/CMA-SurfaceAssistedCorticalParcellation-Manual.pdf?dl=0)

1. Load freesurfer surfaces into 3D Slicer (white matter and cortex)
1. Place several points along the sulcus on the white matter  surface
1. Connect points using a curve using a pathfinding algorithm (Dijkstra's algorithm)
1. Map points from the white matter surface to the cortex surface
1. Place planes identifying the start/stop locations of the parcellation
1. Perform parcellation of the cortex using the planes and sulci definitions

[Video Example](https://www.dropbox.com/s/jolgfuswscm7eb3/brainsuite_demo.wmv?dl=0)

Subtasks:
- [x] [#5: Add curve interpolation along mesh surface](https://github.com/PerkLab/BwhNeuroImagingCollab/issues/5)
- [x] [#6: Add Markup representation for defining planes](https://github.com/PerkLab/BwhNeuroImagingCollab/issues/6)
- [x] [#7: Perform cortical parcellation from plane and sulci definition](https://github.com/PerkLab/BwhNeuroImagingCollab/issues/7)
